### PR TITLE
Update mod files for GPU CoreNEURON execution

### LINKED ISSUE #3: problem for the operation on coreneuron and GPU
Hello, I want to operate netpyne on the coreneuron and gpu. But the package from master branch seems not work well. It still need the external netpyne package. Can you tell me which branch is the final release that I can use to operate? Thanks

### PR DESCRIPTION
**Pull request by iomaganaris**
- Updates mod files for GPU compilation compatibility
- Updates mod files for NEURON 8.2.0+ version
- `IMPORTANT` Enables Random123 random number generator to reproduce spikes between CoreNEURON and NEURON

Fixes #3

### CODE REVIEW

**Comment by iomaganaris** [comment]
Hello @salvadord. Could you have a look at this PR? It's also related to https://github.com/BlueBrain/CoreNeuron/issues/843

**Comment by salvadord** [comment]
thanks @iomaganaris. Do these changes affect the output of the model? since we are creating a repo for the Frontiers paper that should reproduce the paper figs.

I asked @FernandoSBorges to look at this.

**Comment by salvadord** [comment]
fernando: "we aren't using these files, we used the deterministic versions. We can merge "

**Comment by Kim1230** [comment]
Hello, when I download the new version from this merged branch. I get the error from the compilation:
nvvmCompileProgram error 9: NVVM_ERROR_COMPILATION.
Error: /tmp/pgacc5BpnRvkVbbpO.gpu (1989, 22): parse use of undefined value '@_ZN54_INTERNAL_32_x86_64_corenrn_mod2c_StochKv_cpp_b3aebc7710coreneuron14states_StochKvEiiPdPiPNS0_11ThreadDatumEPNS0_9NrnThreadEd'
NVC++-W-0155-Compiler failed to translate accelerator region (see -Minfo messages): Device compiler exited with error status code (x86_64/corenrn/mod2c/StochKv.cpp: 1)
. Although it can generate executable file.
I can't operate it:
Failing in Thread:1
Failing in Thread:1
call to cudaGetSymbolAddress returned error 13: Other

call to cudaGetSymbolAddress returned error 13: Other

Failing in Thread:1
call to cudaGetSymbolAddress returned error 13: Other

Failing in Thread:1
Failing in Thread:1
Failing in Thread:1
call to cudaGetSymbolAddress returned error 13: Other

call to cudaGetSymbolAddress returned error 13: Other

call to cudaGetSymbolAddress returned error 13: Other

Failing in Thread:1
call to cudaGetSymbolAddress returned error 13: Other

Failing in Thread:1
call to cudaGetSymbolAddress returned error 13: Other

Failing in Thread:1
Failing in Thread:1
Failing in Thread:1
Failing in Thread:1
Failing in Thread:1
call to cudaGetSymbolAddress returned error 13: Other

Failing in Thread:1
call to cudaGetSymbolAddress returned error 13: Other

call to cudaGetSymbolAddress returned error 13: Other

Failing in Thread:1
call to cudaGetSymbolAddress returned error 13: Other

call to cudaGetSymbolAddress returned error 13: Other

Can anyone solve the problem? Thanks

**Comment by FernandoSBorges** [comment]
I will check the error. For now I put back the old mods

**Pull request merged**
